#!/bin/bash
# Quick setup script for staging environment

echo "📋 Placement Management Staging Environment Setup"
echo "=================================================="
echo ""
echo "This script helps you set up a staging Firebase project."
echo ""
echo "✅ NEXT STEPS:"
echo ""
echo "1️⃣  Create a new Firebase Project:"
echo "   • Go to https://console.firebase.google.com/"
echo "   • Click 'Add project' and name it: placement-mgmt-staging"
echo "   • Enable Google Analytics (optional)"
echo ""
echo "2️⃣  Get Staging Credentials:"
echo "   • In Firebase Console → Project Settings → Web App"
echo "   • Copy your staging credentials"
echo ""
echo "3️⃣  Update firebase.js:"
echo "   • Edit: src/lib/firebase.js"
echo "   • Replace the stagingConfig placeholders with your credentials"
echo ""
echo "4️⃣  Enable Firestore TTL Policy:"
echo "   • In Firebase Console → Firestore → Settings → TTL Policy"
echo "   • Click 'Create Policy'"
echo "   • TTL Field: __expiresAt"
echo "   • This will auto-delete staging data after 30 days"
echo ""
echo "5️⃣  Update Firestore Rules:"
echo "   • In Firebase Console → Firestore → Rules"
echo "   • Deploy the rules from firestore.rules (already updated)"
echo ""
echo "6️⃣  Run Development (uses staging by default):"
echo "   npm run dev"
echo ""
echo "7️⃣  Build for specific environment:"
echo "   npm run build -- --mode staging    # Staging build"
echo "   npm run build -- --mode production # Production build"
echo ""
echo "📚 For detailed guide, see: STAGING_SETUP.md"
echo ""
