/**
 * Shared mock fixtures for all page logic tests.
 * Mirrors real Firestore document shapes — no mocks/stubs needed.
 */

// ── Students ──────────────────────────────────────────────────────────────────

export const STUDENTS = [
  {
    _id: 's1',
    cohort: { campus: 'Delhi', programme: 'IB', yearCode: '27' },
    name: 'Arjun Mehta',
    roll: 'D27-001',
    email: 'arjun@iift.edu',
    gender: 'Male',
    category: 'General',
    cat: '98.5',
    wx: '24',
    age: '25',
    dob: '1999-04-15',
    pwd: 'no',
    _placed_summer: true,
    _placement_summer: {
      company: 'McKinsey & Company',
      role: 'Business Analyst',
      sector: 'Consulting',
      location: 'Domestic',
      package: '60000',
      via: 'Summer PPO',
      placedAtIso: '2025-04-10T00:00:00.000Z',
      date: '2025-04-10',
    },
    _placed_final: true,
    _placement_final: {
      company: 'Goldman Sachs',
      role: 'Analyst',
      sector: 'BFSI',
      location: 'Domestic',
      package: '3250000',
      via: 'Campus Drive',
      placedAtIso: '2025-11-20T00:00:00.000Z',
      date: '2025-11-20',
    },
  },
  {
    _id: 's2',
    cohort: { campus: 'Delhi', programme: 'IB', yearCode: '27' },
    name: 'Priya Sharma',
    roll: 'D27-002',
    email: 'priya@iift.edu',
    gender: 'Female',
    category: 'OBC',
    cat: '95.2',
    wx: '0',
    age: '23',
    dob: '2001-07-22',
    pwd: 'no',
    _placed_summer: true,
    _placement_summer: {
      company: 'Deloitte',
      role: 'Consultant',
      sector: 'Consulting',
      location: 'Domestic',
      package: '45000',
      via: 'Campus Drive',
      placedAtIso: '2025-04-12T00:00:00.000Z',
      date: '2025-04-12',
    },
    _placed_final: false,
    _placement_final: null,
  },
  {
    _id: 's3',
    cohort: { campus: 'Delhi', programme: 'IB', yearCode: '27' },
    name: 'Rohit Kumar',
    roll: 'D27-003',
    email: 'rohit@iift.edu',
    gender: 'Male',
    category: 'SC',
    cat: '91.0',
    wx: '36',
    age: '27',
    dob: '1997-01-10',
    pwd: 'yes',
    _placed_summer: false,
    _placement_summer: null,
    _placed_final: true,
    _placement_final: {
      company: 'Tata Consultancy Services',
      role: 'Manager',
      sector: 'IT / Tech',
      location: 'Domestic',
      package: '1500000',
      via: 'Campus Drive',
      placedAtIso: '2025-12-01T00:00:00.000Z',
      date: '2025-12-01',
    },
  },
  {
    _id: 's4',
    cohort: { campus: 'Delhi', programme: 'IB', yearCode: '27' },
    name: 'Sneha Patel',
    roll: 'D27-004',
    email: 'sneha@iift.edu',
    gender: 'Female',
    category: 'General',
    cat: '99.1',
    wx: '12',
    age: '24',
    dob: '2000-09-05',
    pwd: 'no',
    _placed_summer: false,
    _placement_summer: null,
    _placed_final: false,
    _placement_final: null,
  },
  {
    _id: 's5',
    cohort: { campus: 'Delhi', programme: 'BA', yearCode: '27' },
    name: 'Vikram Nair',
    roll: 'BA27-001',
    email: 'vikram@iift.edu',
    gender: 'Male',
    category: 'General',
    cat: '88.3',
    wx: '8',
    age: '22',
    dob: '2002-03-20',
    pwd: 'no',
    _placed_summer: true,
    _placement_summer: {
      company: 'Asian Paints',
      role: 'Management Trainee',
      sector: 'Manufacturing',
      location: 'Domestic',
      package: '35000',
      via: 'Campus Drive',
      placedAtIso: '2024-04-15T00:00:00.000Z',
      date: '2024-04-15',
    },
    _placed_final: false,
    _placement_final: null,
  },
  {
    _id: 's6',
    cohort: { campus: 'Kakinada', programme: 'IB', yearCode: '27' },
    name: 'Ananya Reddy',
    roll: 'K27-001',
    email: 'ananya@iift.edu',
    gender: 'Female',
    category: 'ST',
    cat: '87.5',
    wx: '48',
    age: '28',
    dob: '1996-11-30',
    pwd: 'no',
    _placed_summer: true,
    _placement_summer: {
      company: 'Goldman Sachs',
      role: 'Analyst',
      sector: 'BFSI',
      location: 'International',
      package: '80000',
      via: 'Campus Drive',
      placedAtIso: '2025-04-08T00:00:00.000Z',
      date: '2025-04-08',
    },
    _placed_final: true,
    _placement_final: {
      company: 'McKinsey & Company',
      role: 'Associate',
      sector: 'Consulting',
      location: 'International',
      package: '5000000',
      via: 'PPO',
      placedAtIso: '2025-11-15T00:00:00.000Z',
      date: '2025-11-15',
    },
  },
]

// ── Intel records ─────────────────────────────────────────────────────────────

export const INTEL_RECORDS = [
  {
    _id: 'i1',
    recruiterId: 'MCKINSEYCOMPANY',
    recruiterName: 'McKinsey & Company',
    alias: 'McKinsey',
    placementYear: 2025,
    placementCycle: 'Finals',
    collegeName: 'IIM Ahmedabad',
    campus: '',
    program: 'MBA',
    sector: 'Consulting',
    function: 'Strategy',
    rolesMentioned: 'Associate, Business Analyst',
    recruiterType: 'MNC',
    internationalOpp: true,
    internationalLoc: 'Global',
    numberOfOffers: 5,
    compensation: '45 LPA',
    poc: { name: 'Rahul Shah', email: 'r.shah@mckinsey.com', phone: '9876543210' },
    notes: 'Very process-heavy',
    _deleted: false,
    _dedupKey: 'MCKINSEYCOMPANY::IIM AHMEDABAD::2025::FINALS::MBA',
  },
  {
    _id: 'i2',
    recruiterId: 'MCKINSEYCOMPANY',
    recruiterName: 'McKinsey & Company',
    alias: 'McKinsey',
    placementYear: 2024,
    placementCycle: 'Finals',
    collegeName: 'XLRI',
    campus: '',
    program: 'MBA',
    sector: 'Consulting',
    function: 'Strategy',
    rolesMentioned: 'Associate',
    recruiterType: 'MNC',
    internationalOpp: false,
    internationalLoc: '',
    numberOfOffers: 3,
    compensation: '42 LPA',
    poc: { name: '', email: '', phone: '' },
    notes: '',
    _deleted: false,
    _dedupKey: 'MCKINSEYCOMPANY::XLRI::2024::FINALS::MBA',
  },
  {
    _id: 'i3',
    recruiterId: 'GOLDMANSACHS',
    recruiterName: 'Goldman Sachs',
    alias: 'GS',
    placementYear: 2025,
    placementCycle: 'Summer',
    collegeName: 'IIM Bangalore',
    campus: '',
    program: 'MBA',
    sector: 'BFSI',
    function: 'Investment Banking',
    rolesMentioned: 'Analyst',
    recruiterType: 'MNC',
    internationalOpp: true,
    internationalLoc: 'Singapore',
    numberOfOffers: 8,
    compensation: '55 LPA',
    poc: { name: 'Anjali Menon', email: 'a.menon@gs.com', phone: '' },
    notes: 'Case + technical rounds',
    _deleted: false,
    _dedupKey: 'GOLDMANSACHS::IIM BANGALORE::2025::SUMMER::MBA',
  },
  {
    _id: 'i4',
    recruiterId: 'ASIANPAINTS',
    recruiterName: 'Asian Paints',
    alias: 'AP',
    placementYear: 2025,
    placementCycle: 'Finals',
    collegeName: 'IIM Calcutta',
    campus: '',
    program: 'MBA',
    sector: 'Manufacturing',
    function: 'Marketing',
    rolesMentioned: 'Product Manager',
    recruiterType: 'Indian Conglomerate',
    internationalOpp: false,
    internationalLoc: '',
    numberOfOffers: 2,
    compensation: '22 LPA',
    poc: { name: '', email: '', phone: '' },
    notes: '',
    _deleted: false,
    _dedupKey: 'ASIANPAINTS::IIM CALCUTTA::2025::FINALS::MBA',
  },
  {
    _id: 'i5',
    recruiterId: 'CREDITSUITEME',
    recruiterName: 'Credit Suisse',
    alias: 'CS',
    placementYear: 2023,
    placementCycle: 'Finals',
    collegeName: 'IIM Ahmedabad',
    campus: '',
    program: 'MBA',
    sector: 'BFSI',
    function: 'Markets',
    rolesMentioned: 'Analyst',
    recruiterType: 'MNC',
    internationalOpp: false,
    internationalLoc: '',
    numberOfOffers: 4,
    compensation: '38 LPA',
    poc: { name: '', email: '', phone: '' },
    notes: 'No longer active (acquired by UBS)',
    _deleted: false,
    _dedupKey: 'CREDITSUITEME::IIM AHMEDABAD::2023::FINALS::MBA',
  },
]

// ── Pending changes ───────────────────────────────────────────────────────────

export const PENDING_CHANGES = [
  {
    _id: 'pc1',
    type: 'place',
    status: 'pending',
    cohort: '27-Delhi-IB',
    season: 'final',
    studentId: 's4',
    studentName: 'Sneha Patel',
    studentRoll: 'D27-004',
    placementDetails: { company: 'BCG', role: 'Consultant', via: 'Campus Drive' },
    createdBy: 'uid-jay',
    createdAt: { toDate: () => new Date('2025-11-25T10:00:00Z') },
  },
  {
    _id: 'pc2',
    type: 'unplace',
    status: 'pending',
    cohort: '27-Delhi-IB',
    season: 'summer',
    studentId: 's2',
    studentName: 'Priya Sharma',
    studentRoll: 'D27-002',
    currentCompany: 'Deloitte',
    createdBy: 'uid-aditya',
    createdAt: { toDate: () => new Date('2025-11-26T09:00:00Z') },
  },
  {
    _id: 'pc3',
    type: 'import',
    status: 'approved',
    cohort: '27-Delhi-IB',
    rowCount: 60,
    replaceExisting: false,
    createdBy: 'uid-basil',
    approvedBy: 'uid-jay',
    createdAt: { toDate: () => new Date('2025-10-01T08:00:00Z') },
  },
  {
    _id: 'pc4',
    type: 'delete',
    status: 'rejected',
    cohort: '27-Delhi-IB',
    studentId: 's3',
    studentName: 'Rohit Kumar',
    studentRoll: 'D27-003',
    createdBy: 'uid-lakshyc',
    createdAt: { toDate: () => new Date('2025-11-10T14:00:00Z') },
  },
  {
    _id: 'pc5',
    type: 'place',
    status: 'pending',
    cohort: '27-Kakinada-IB',
    season: 'final',
    studentId: 's6',
    studentName: 'Ananya Reddy',
    studentRoll: 'K27-001',
    placementDetails: { company: 'Bain & Company', role: 'Consultant', via: 'Campus Drive' },
    createdBy: 'uid-ranishka',
    createdAt: { toDate: () => new Date('2025-11-27T11:00:00Z') },
  },
]

// ── Opportunities ─────────────────────────────────────────────────────────────

export const OPPORTUNITIES = [
  {
    _id: 'o1',
    title: 'Management Consulting Role',
    company: 'BCG',
    type: 'Campus Drive',
    stage: 'Shortlist Released',
    sector: 'Consulting',
    targetBatch: '27-Delhi-IB',
    ctcRange: '30-40 LPA',
    roles: 'Consultant, Senior Consultant',
    deadline: { toDate: () => new Date('2025-12-15T00:00:00Z') },
    notes: 'Pre-placement talk on Dec 10',
    _deleted: false,
  },
  {
    _id: 'o2',
    title: 'IB Analyst Program',
    company: 'Goldman Sachs',
    type: 'Campus Drive',
    stage: 'Offer Released',
    sector: 'BFSI',
    targetBatch: '27-Delhi-IB',
    ctcRange: '40-55 LPA',
    roles: 'Analyst',
    deadline: { toDate: () => new Date('2025-11-30T00:00:00Z') },
    notes: '',
    _deleted: false,
  },
  {
    _id: 'o3',
    title: 'Summer Internship',
    company: 'Hindustan Unilever',
    type: 'Campus Drive',
    stage: 'Exploring',
    sector: 'FMCG',
    targetBatch: '27-Delhi-IB',
    ctcRange: '35-42 LPA',
    roles: 'Management Trainee',
    deadline: null,
    notes: 'Follow up with POC',
    _deleted: false,
  },
]

// ── Helper: get students by cohort ────────────────────────────────────────────

export function studentCohort(s) {
  if (!s.cohort) return ''
  if (typeof s.cohort === 'string') return s.cohort
  const { campus, programme, yearCode } = s.cohort
  return `${yearCode}-${campus}-${programme}`
}

export const DELHI_IB_STUDENTS = STUDENTS.filter(
  s => studentCohort(s) === '27-Delhi-IB'
)

export const ALL_DELHI_STUDENTS = STUDENTS.filter(
  s => studentCohort(s).includes('Delhi')
)
